#!/bin/bash

# delete old files
sudo rm -rf app
sudo rm -rf etc
sudo rm -rf nginx
sudo rm -rf pgsql

cp -R source/app .
cp -R source/etc .
cp -R source/nginx .
cp -R source/pgsql .

# removing prefills
sudo rm -rf prefill_pddikti/*
cp source/prefill/btp/* prefill_pddikti/
