#!/bin/bash

# delete old files
sudo rm -rf app
sudo rm -rf etc
sudo rm -rf nginx
sudo rm -rf pgsql
sudo rm -rf prefill_pddikti

cp -R source/app .
cp -R source/etc .
cp -R source/nginx .
cp -R source/pgsql .
cp -R source/prefill_pddikti .