services:

  # PgSQL Service
  db-pddikti:
    image: postgres:12
    command:
      - "postgres"
      - "-p"
      - "54333"
    environment:
      TZ: "Asia/Jakarta"
    tty: true
    volumes:
      - ${APP_PATH_HOST}/pgsql/data:/var/lib/postgresql/data
      - ${APP_PATH_HOST}/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    deploy:
      restart_policy:
        condition: any

  # Application
  app-pddikti:
    image: unuha/feeder:latest
    ports:
      - target: 8100
        published: 8200
        protocol: tcp
        mode: host
    tty: true
    environment:
      TZ: "Asia/Jakarta"
      SERVICE_NAME: "app"
      SERVICE_TAGS: "1.0.2"
      PGHOST: "db-pddikti"
      PGPORT: 54333
    volumes:
      - ${APP_PATH_HOST}/prefill_pddikti:/prefill_pddikti
      - ${APP_PATH_HOST}/logs/supervisor:/var/log/supervisor
    depends_on:
      - db-pddikti
    deploy:
      restart_policy:
        condition: any
